nohup ./run.sh 0 1 tanhWxhb sib-sig-tanhsczi &
nohup ./run.sh 0 2 tanhWxhb sib-sig-tanhsczi &
nohup ./run.sh 0 3 tanhWxhb sib-sig-tanhsczi &
nohup ./run.sh 0 4 tanhWxhb sib-sig-tanhsczi &
nohup ./run.sh 0 1 tanhWxb sib-sig-tanhsczi &
nohup ./run.sh 0 2 tanhWxb sib-sig-tanhsczi &
nohup ./run.sh 0 3 tanhWxb sib-sig-tanhsczi &
nohup ./run.sh 0 4 tanhWxb sib-sig-tanhsczi &
nohup ./run.sh 0 1 tanhWxh sib-sig-tanhsczi &
nohup ./run.sh 0 2 tanhWxh sib-sig-tanhsczi &
nohup ./run.sh 0 3 tanhWxh sib-sig-tanhsczi &
nohup ./run.sh 0 4 tanhWxh sib-sig-tanhsczi &
nohup ./run.sh 1 1 tanhWx sib-sig-tanhsczi &
nohup ./run.sh 1 2 tanhWx sib-sig-tanhsczi &
nohup ./run.sh 1 3 tanhWx sib-sig-tanhsczi &
nohup ./run.sh 1 4 tanhWx sib-sig-tanhsczi &
nohup ./run.sh 1 1 Wx sib-sig-tanhsczi &
nohup ./run.sh 1 2 Wx sib-sig-tanhsczi &
nohup ./run.sh 1 3 Wx sib-sig-tanhsczi &
nohup ./run.sh 1 4 Wx sib-sig-tanhsczi &
nohup ./run.sh 1 1 Wxb sib-sig-tanhsczi &
nohup ./run.sh 1 2 Wxb sib-sig-tanhsczi &
nohup ./run.sh 1 3 Wxb sib-sig-tanhsczi &
nohup ./run.sh 1 4 Wxb sib-sig-tanhsczi &
nohup ./run.sh 2 1 Wxh sib-sig-tanhsczi &
nohup ./run.sh 2 2 Wxh sib-sig-tanhsczi &
nohup ./run.sh 2 3 Wxh sib-sig-tanhsczi &
nohup ./run.sh 2 4 Wxh sib-sig-tanhsczi &
nohup ./run.sh 2 1 Wxhb sib-sig-tanhsczi &
nohup ./run.sh 2 2 Wxhb sib-sig-tanhsczi &
nohup ./run.sh 2 3 Wxhb sib-sig-tanhsczi &
nohup ./run.sh 2 4 Wxhb sib-sig-tanhsczi &
